eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://service-registry-uat-34ktyktxna-el.a.run.app/eureka/
  instance:
    hostname: localhost
